// Original learning material. All lesson content is bundled locally.
export const lessons = [
  {
    id: 'last-seat',
    title: 'The Last Seat',
    subtitle: '終電の一つ前。ひと言から始まる、小さな出会い。',
    level: 'A1',
    category: 'STORY',
    minutes: 4,
    color: '#596B9B',
    scene: '夜の電車。窓には街の明かり。空席に、小さな紙袋が一つ。',
    outcome: '「Can I …?」で、相手に短く許可を求める',
    lines: [
      { speaker: 'Mina', en: 'Excuse me. Can I sit here?', ja: 'すみません。ここに座ってもいいですか？', note: 'can は文の中で弱く短くなることがあります。お願いの中心になる sit と here に耳を向けましょう。' },
      { speaker: 'Leo', en: 'Of course. Let me move my bag.', ja: 'もちろん。袋をどけますね。', note: 'move my は子音が続く部分。音の境目より、ひとまとまりの動作として聞きましょう。' },
      { speaker: 'Mina', en: 'Thank you. Is that a cake?', ja: 'ありがとう。それはケーキですか？', note: 'that a は、that の最後の子音と a がつながって聞こえることがあります。' },
      { speaker: 'Leo', en: 'Yes. It is for my sister.', ja: 'はい。妹へのケーキです。', note: 'for は弱く発音されることがあります。相手を表す my sister を聞き取りましょう。' },
      { speaker: 'Mina', en: "I'm Mina. Can I ask her name?", ja: '私はミナです。妹さんの名前を聞いてもいいですか？', note: 'Can I ask は、語ごとに区切らず続けて言われることがあります。まず ask を手がかりに意味をつかみましょう。' },
      { speaker: 'Leo', en: 'Mina. Just like you!', ja: 'ミナ。あなたと同じ名前ですね！', note: 'like you では二つの語が滑らかにつながります。驚きを表す you が強くなることがあります。' },
    ],
    question: { prompt: '紙袋に入っていたケーキは誰のため？', options: ['レオの妹', 'ミナの友だち', '電車の運転士'], correct: 0, explanation: '「It is for my sister.」の for は「〜のために」。レオの妹へのケーキです。' },
    transfer: { prompt: '図書館で、隣の人のペンを借りたい。許可を求めるなら？', options: ['You can borrow my pen.', 'Can I borrow your pen?', 'Where is my pen?'], correct: 1, explanation: 'Can I + 動詞で「〜してもいいですか？」。相手のペンなので your pen を使います。' },
    practice: [
      { prompt: 'Ask if you can sit here.', answer: 'Can I sit here?', ja: 'ここに座ってもいいですか？' },
      { prompt: 'Ask if you can open the window.', answer: 'Can I open the window?', ja: '窓を開けてもいいですか？' },
      { prompt: 'Ask if you can take a photo.', answer: 'Can I take a photo?', ja: '写真を撮ってもいいですか？' },
    ],
  },
  {
    id: 'coffee-for-two',
    title: 'Coffee for Two',
    subtitle: 'いつもの一杯。今日は、もう一杯。',
    level: 'A2',
    category: 'STORY',
    minutes: 4,
    color: '#B78159',
    scene: '朝の小さなカフェ。入口のベルが鳴り、二人分の湯気が立つ。',
    outcome: '「I’d like …」で注文し、「Could I have …?」で希望を添える',
    lines: [
      { speaker: 'Kai', en: "I'd like a small coffee, please.", ja: '小さいコーヒーを一つお願いします。', note: 'I’d は I would の短縮形です。like a は子音と母音が続き、つながって聞こえることがあります。' },
      { speaker: 'Barista', en: 'For here or to go?', ja: '店内ですか、お持ち帰りですか？', note: 'or と to は弱く短くなりやすい語。here と go を手がかりに、二つの選択肢を聞き取りましょう。' },
      { speaker: 'Kai', en: 'For here. Could I have some milk?', ja: '店内で。ミルクもいただけますか？', note: 'Could I は語の境目が滑らかになることがあります。疑問文の形のまま、一息で練習してみましょう。' },
      { speaker: 'Barista', en: 'Sure. Anything else?', ja: 'もちろんです。ほかには？', note: 'Anything else? は接客でよく使う短い問いです。anything の th では舌先を軽く歯の間に置きます。' },
      { speaker: 'Kai', en: "Actually, I'd like two coffees. My dad is outside.", ja: 'やっぱり、コーヒーを二つお願いします。父が外にいるんです。', note: '注文を変える two が強くなると、「一つではなく二つ」という新しい情報が伝わります。' },
    ],
    question: { prompt: 'カイがコーヒーを二つ注文した理由は？', options: ['一杯目をこぼしたから', '店員に一杯あげたいから', '外にお父さんがいるから'], correct: 2, explanation: '最後の「My dad is outside.」が理由です。actually は、ここでは注文を言い直す合図になっています。' },
    transfer: { prompt: 'パン屋でクロワッサンを二つ、丁寧に注文するなら？', options: ["I'd like two croissants, please.", 'I like croissants every day.', 'Could you like two croissants?'], correct: 0, explanation: 'I’d like は「〜をお願いします」という丁寧な希望。I like は単に「〜が好き」です。' },
    practice: [
      { prompt: 'Order a small tea politely.', answer: "I'd like a small tea, please.", ja: '小さい紅茶を一つお願いします。' },
      { prompt: 'Ask for some water politely.', answer: 'Could I have some water?', ja: 'お水をいただけますか？' },
      { prompt: 'Say that your order is to go.', answer: 'To go, please.', ja: '持ち帰りでお願いします。' },
    ],
  },
  {
    id: 'yellow-umbrella',
    title: 'The Yellow Umbrella',
    subtitle: 'なくした傘と、思いがけない忘れ物。',
    level: 'A2',
    category: 'STORY',
    minutes: 5,
    color: '#B5973D',
    scene: '雨上がりの書店。閉店まであと五分。傘立てに一本だけ残っている。',
    outcome: '「might」で確信のないことを伝え、確認をお願いする',
    lines: [
      { speaker: 'Aya', en: 'I might have left my umbrella here.', ja: 'ここに傘を忘れたかもしれません。', note: 'might have の have は弱く短く発音されることがあります。might は「確かではない」という意味の手がかりです。' },
      { speaker: 'Clerk', en: 'What does it look like?', ja: 'どんな傘ですか？', note: 'does it は子音と母音がつながりやすい部分です。look like を「どんな見た目か」というまとまりで聞きましょう。' },
      { speaker: 'Aya', en: 'It is yellow, with a blue handle.', ja: '黄色で、持ち手が青いです。', note: 'yellow、blue、handle が見た目を伝える大事な語。色を言う部分に少し強さを置くと伝わりやすくなります。' },
      { speaker: 'Clerk', en: 'This might be yours. Could you check?', ja: 'これはあなたのかもしれません。確認してもらえますか？', note: 'Could you は話す速さや話者によって、音がまとまって聞こえることがあります。二語だと意識して聞いてみましょう。' },
      { speaker: 'Aya', en: 'Yes, it is! And my book is in the bag!', ja: 'そうです！ それに、本も袋の中にありました！', note: 'is in は続けると境目が目立ちにくくなります。book と bag を聞いて、何がどこにあるか整理しましょう。' },
    ],
    question: { prompt: 'アヤの傘の特徴は？', options: ['青い傘で、黄色い持ち手', '黄色い傘で、青い持ち手', '黄色い傘で、黒い持ち手'], correct: 1, explanation: '「yellow, with a blue handle」。with は、ここでは「〜の付いた」という意味です。' },
    transfer: { prompt: '鍵がコートのポケットにあるかもしれない。確信がないことを伝えるなら？', options: ['My keys are always in my coat.', 'My keys cannot be in my coat.', 'My keys might be in my coat.'], correct: 2, explanation: 'might be は「〜にあるかもしれない」。確かめる前の可能性を表せます。' },
    practice: [
      { prompt: 'Say that your phone may be at home. Use might.', answer: 'My phone might be at home.', ja: '携帯は家にあるかもしれません。' },
      { prompt: 'Ask someone to check politely.', answer: 'Could you check?', ja: '確認してもらえますか？' },
      { prompt: 'Say that you may have left your bag here. Use might.', answer: 'I might have left my bag here.', ja: 'ここにかばんを忘れたかもしれません。' },
    ],
  },
  {
    id: 'different-kind-of-saturday',
    title: 'A Different Saturday',
    subtitle: '予定どおりじゃない日が、いい日になる。',
    level: 'B1',
    category: 'STORY',
    minutes: 5,
    color: '#718A75',
    scene: '土曜の公園前。門には休園の札。二人の手には、まだ温かいパン。',
    outcome: '「What if we …?」で代案を出し、自然に予定を変える',
    lines: [
      { speaker: 'Ren', en: 'The park is closed. There goes our picnic.', ja: '公園、閉まってる。ピクニックはだめになったね。', note: 'There goes our picnic. は、予定がうまくいかなくなったときの表現。picnic に強さを置くと残念な気持ちが伝わります。' },
      { speaker: 'Emi', en: 'What if we went to the river instead?', ja: '代わりに川へ行くのはどう？', note: 'What if は t と次の母音が続く部分。went は過去の出来事ではなく、ここでは控えめな提案を作っています。' },
      { speaker: 'Ren', en: 'It is a bit far, and I am hungry.', ja: 'ちょっと遠いし、おなかがすいたよ。', note: 'a bit は弱い a と、意味の中心になる bit のリズムに注目。and は会話では短くなることがあります。' },
      { speaker: 'Emi', en: 'Then how about the bench outside the library?', ja: 'じゃあ、図書館の外のベンチは？', note: 'how about は続けて聞こえることがあります。bench と library が、提案している場所の手がかりです。' },
      { speaker: 'Ren', en: 'That works. We have bread and a view of the sky.', ja: 'それでいこう。パンもあるし、空も見える。', note: 'That works. は「それで大丈夫」という賛成。works の最後には k と s が続くので、母音を足さずに練習しましょう。' },
    ],
    question: { prompt: '二人は最終的にどこで食べることにした？', options: ['図書館の外のベンチ', '川のそば', '閉まっている公園の中'], correct: 0, explanation: 'エミがベンチを提案し、レンが「That works.」と賛成しています。最初の川の案には決まっていません。' },
    transfer: { prompt: '行きたい映画が満席。代わりに家で映画を見る提案をするなら？', options: ['What did we watch at home?', 'What if we watched a movie at home instead?', 'We never watch movies at home.'], correct: 1, explanation: 'What if we + 過去形で、控えめに代案を出せます。instead は「代わりに」という意味です。' },
    practice: [
      { prompt: 'Suggest taking the bus instead. Start with What if.', answer: 'What if we took the bus instead?', ja: '代わりにバスに乗るのはどう？' },
      { prompt: 'Suggest meeting on Sunday. Start with How about.', answer: 'How about meeting on Sunday?', ja: '日曜日に会うのはどう？' },
      { prompt: 'Agree to a practical suggestion in two words.', answer: 'That works.', ja: 'それで大丈夫。それでいこう。' },
    ],
  },
  {
    id: 'one-more-lemon',
    title: 'One More Lemon',
    subtitle: '初めてのパスタ。レシピより大切な、ひと口。',
    level: 'A2',
    category: 'STORY',
    minutes: 4,
    color: '#B96951',
    scene: '小さなキッチン。二人で作ったパスタを、一つの鍋から味見する。',
    outcome: '「too + 形容詞」で困りごとを伝え、「Try + -ing」で方法を提案する',
    lines: [
      { speaker: 'Noa', en: 'The pasta is too dry.', ja: 'パスタがぱさぱさしすぎているね。', note: 'too と dry が中心の情報です。too は「とても」ではなく、ここでは「程度が過ぎる」という意味です。' },
      { speaker: 'Haru', en: 'Try adding a little pasta water.', ja: 'ゆで汁を少し加えてみて。', note: 'adding a は最後の子音と次の母音が続きます。Try adding を、試してみる方法のまとまりとして聞きましょう。' },
      { speaker: 'Noa', en: 'That is better. Can you pass the lemon?', ja: 'よくなった。レモンを取ってくれる？', note: 'Can you は弱く短くなることがあります。お願いの内容は pass the lemon の部分です。' },
      { speaker: 'Haru', en: 'Here you go. Just a little juice!', ja: 'はい、どうぞ。果汁はほんの少しね！', note: 'Here you go. は物を渡すときのひとまとまり。Just を強くすると「ほんの少し」という気持ちが伝わります。' },
      { speaker: 'Noa', en: 'Perfect. Now we only need two forks.', ja: 'ばっちり。あとはフォークが二本あればいいね。', note: 'forks の語末は k と s が続きます。最後に母音を足さず、短く終えてみましょう。' },
    ],
    question: { prompt: '最初にパスタへ加えるよう提案したものは？', options: ['レモンを丸ごと一つ', 'ゆで汁を少し', 'フォークを二本'], correct: 1, explanation: '「Try adding a little pasta water.」が最初の提案。pasta water はパスタのゆで汁です。' },
    transfer: { prompt: '友だちが「かばんが重すぎる」と困っている。荷物を減らす方法を提案するなら？', options: ['Try taking out a few books.', 'Try carrying more books.', 'The bag is very blue.'], correct: 0, explanation: 'Try + 動詞の -ing 形で「試しに〜してみて」。taking out は、ここでは本をかばんから取り出すことです。' },
    practice: [
      { prompt: 'Say that the music is louder than you want. Use too.', answer: 'The music is too loud.', ja: '音楽の音が大きすぎます。' },
      { prompt: 'Suggest opening the window. Use Try.', answer: 'Try opening the window.', ja: '窓を開けてみて。' },
      { prompt: 'Ask someone to pass the salt.', answer: 'Can you pass the salt?', ja: '塩を取ってくれる？' },
    ],
  },
  {
    id: 'inside-a-raindrop',
    title: 'Inside a Raindrop',
    subtitle: '雨になるまでを、短い英語でたどる。',
    level: 'A2',
    category: 'EXPLAINER',
    minutes: 4,
    color: '#648CA2',
    scene: '窓に落ちる一滴。その前に、空では何が起きていたのだろう。',
    outcome: '「First / Then / Finally」で、順番のある説明をする',
    lines: [
      { speaker: 'Narrator', en: 'Water can change into a gas called water vapor.', ja: '水は水蒸気という気体に変わることがあります。', note: 'called の後の water vapor が気体の名前です。意味の区切りを意識して、水の変化を聞き取りましょう。' },
      { speaker: 'Narrator', en: 'Here is one way that rain forms.', ja: '雨ができる仕組みの一つを見てみましょう。', note: 'Here is は語の境目が滑らかになりやすい部分。one way は「唯一の仕組みではない」という意味です。' },
      { speaker: 'Narrator', en: 'First, moist air rises and cools.', ja: 'まず、湿った空気が上昇して冷えます。', note: 'First の後で少し区切ると、順序が伝わります。rises と cools の二つの動きを聞きましょう。' },
      { speaker: 'Narrator', en: 'Then, water vapor forms tiny drops around small particles.', ja: '次に、水蒸気が小さな粒子の周りで小さな水滴になります。', note: 'Then が次の段階の合図です。tiny drops と small particles をそれぞれひとまとまりで聞きましょう。' },
      { speaker: 'Narrator', en: 'In a cloud, some drops join together and grow.', ja: '雲の中では、一部の水滴がくっついて大きくなります。', note: 'In a は子音と母音がつながりやすい部分。join together and grow は二つの変化を順に表しています。' },
      { speaker: 'Narrator', en: 'Finally, large enough drops can fall as rain.', ja: '最後に、十分に大きくなった水滴が雨として落ちてくることがあります。', note: 'large enough では形容詞の後に enough が来ます。Finally を合図に、説明の最後の段階をつかみましょう。' },
    ],
    question: { prompt: 'この説明で、雲の中の水滴が大きくなるのはどうして？', options: ['水滴が光に変わるから', 'すべての雲が一度に消えるから', '水滴どうしがくっつくから'], correct: 2, explanation: '「some drops join together and grow」が根拠です。これは雨ができる仕組みの一つで、氷の粒が関わる場合もあります。' },
    transfer: { prompt: 'お茶のいれ方を「まず湯を沸かし、次に注ぐ」と説明するなら？', options: ['Finally, boil water. First, drink it.', 'First, boil some water. Then, pour it into the cup.', 'Then is a cup of water.'], correct: 1, explanation: 'First で最初の手順、Then で次の手順を示します。身近な作業の説明にも使えます。' },
    practice: [
      { prompt: 'Tell someone the first step is to wash their hands. Use First.', answer: 'First, wash your hands.', ja: 'まず、手を洗ってください。' },
      { prompt: 'Tell someone the next step is to cut the bread. Use Then.', answer: 'Then, cut the bread.', ja: '次に、パンを切ってください。' },
      { prompt: 'Tell someone the last step is to enjoy their sandwich. Use Finally.', answer: 'Finally, enjoy your sandwich.', ja: '最後に、サンドイッチをおいしく食べましょう。' },
    ],
  },
  {
    id: 'a-place-in-the-shade',
    title: 'A Place in the Shade',
    subtitle: '同じ公園なのに、木の下が涼しく感じるのはなぜ？',
    level: 'B1',
    category: 'EXPLAINER',
    minutes: 5,
    color: '#688B6C',
    scene: '夏の歩道から、木陰へ一歩。肌に届く熱の違いを、言葉にする。',
    outcome: '「because」で理由をつなぎ、現象を簡潔に説明する',
    lines: [
      { speaker: 'Narrator', en: 'Sunlight can warm your skin and the ground.', ja: '太陽の光は、肌や地面を温めます。', note: 'skin and the ground は二つの対象。and と the は弱くなりやすく、skin と ground が聞き取りの手がかりです。' },
      { speaker: 'Narrator', en: 'Shade blocks direct sunlight.', ja: '日陰では、太陽の光が直接当たるのを防げます。', note: 'blocks direct は子音が続きます。語尾を一音ずつ強くするより、blocks と direct の二つの語を意識しましょう。' },
      { speaker: 'Narrator', en: 'You can feel cooler because less sunlight reaches your body.', ja: '体に届く太陽の光が減るので、涼しく感じることがあります。', note: 'because の後が理由です。cooler と less sunlight を手がかりに、結果と理由を分けて聞きましょう。' },
      { speaker: 'Narrator', en: 'The air temperature may be similar nearby.', ja: 'すぐ近くでは、空気の温度はあまり変わらないこともあります。', note: 'may は「そうかもしれない」という幅を持たせる語。temperature は音節ごとに同じ強さで読む必要はありません。' },
      { speaker: 'Narrator', en: 'How hot you feel also depends on wind and humidity.', ja: 'どのくらい暑く感じるかは、風や湿度にも左右されます。', note: 'depends on は depends の最後の子音と on の母音がつながることがあります。wind と humidity が、ここで加わる二つの条件です。' },
    ],
    question: { prompt: '日陰で涼しく感じる理由として、説明されているのは？', options: ['体に届く太陽の光が減るから', '日陰では空気が必ず10度下がるから', '日陰には湿度がないから'], correct: 0, explanation: '日陰では直射日光による熱を受けにくくなります。体感の違いと、空気の温度の違いは同じではありません。' },
    transfer: { prompt: 'カフェで「窓の近くは明るいので、そこに座りたい」と理由を伝えるなら？', options: ['I sit near the window, but it has a name.', 'The window is because I sit.', 'I want to sit near the window because it is bright there.'], correct: 2, explanation: 'because の前に希望、後に理由を置きます。「明るいから」という理由が自然につながっています。' },
    practice: [
      { prompt: 'Say you need water because you are thirsty.', answer: 'I need water because I am thirsty.', ja: 'のどが渇いているので、水が必要です。' },
      { prompt: 'Say you are walking because the station is close.', answer: 'I am walking because the station is close.', ja: '駅が近いので、歩いています。' },
      { prompt: 'Say you like this room because it is quiet.', answer: 'I like this room because it is quiet.', ja: '静かなので、この部屋が好きです。' },
    ],
  },
  {
    id: 'a-voice-comes-back',
    title: 'A Voice Comes Back',
    subtitle: '声がもう一度聞こえる。その小さな不思議。',
    level: 'A2',
    category: 'EXPLAINER',
    minutes: 4,
    color: '#89769C',
    scene: '静かな谷に「Hello」。少し遅れて、遠くから同じ声が返ってくる。',
    outcome: '「If …, …」で、条件と起こりうることをつなぐ',
    lines: [
      { speaker: 'Narrator', en: 'Sound travels through air as waves.', ja: '音は、空気の中を波として伝わります。', note: 'Sound と waves が説明の中心です。through の th は、舌先を軽く歯の間に置いて息を出します。' },
      { speaker: 'Narrator', en: 'If sound reaches a hard surface, some of it can bounce back.', ja: '音が硬い面に届くと、その一部が跳ね返ることがあります。', note: 'If から surface までが条件です。そこで軽く区切ると、後ろの結果と分けて理解しやすくなります。' },
      { speaker: 'Narrator', en: 'If it returns after a clear delay, you may hear an echo.', ja: 'はっきりとした時間差で戻ってくると、反響が聞こえることがあります。', note: 'hear an echo は子音と母音が続く箇所があります。an echo を二語のまとまりとして意識しましょう。' },
      { speaker: 'Narrator', en: 'A distant cliff can send your voice back to you.', ja: '離れた崖が、あなたの声を跳ね返してくることがあります。', note: 'back to you の to は弱くなりやすい語。back が「戻る」という方向の手がかりになります。' },
      { speaker: 'Narrator', en: 'Soft materials absorb some sound, so the echo may be weaker.', ja: '柔らかい素材は音の一部を吸収するため、反響が弱くなることがあります。', note: 'so の後が結果です。may は、素材や状況によって変わる可能性を表しています。' },
    ],
    question: { prompt: '反響として同じ音をもう一度聞くには、どんなことが必要？', options: ['音が光に変わること', '跳ね返った音が、はっきりした時間差で戻ること', '音がまったく動かないこと'], correct: 1, explanation: '音が反射するだけでなく、元の音と区別できる時間差があると、反響として聞こえることがあります。' },
    transfer: { prompt: '散歩の相談で「雨が降ったら、バスに乗れるよ」と条件付きの案を出すなら？', options: ['If it rains, we can take the bus.', 'It rains because the bus is here.', 'If the bus, we rain.'], correct: 0, explanation: 'If + 主語 + 動詞で条件を示し、その後にできることを続けます。未来の可能性でも、ここでは If it rains と現在形を使います。' },
    practice: [
      { prompt: 'Offer some tea if your friend is cold.', answer: 'If you are cold, I can make some tea.', ja: '寒いなら、お茶をいれられるよ。' },
      { prompt: 'Suggest walking if it is sunny.', answer: 'If it is sunny, we can walk.', ja: '晴れていたら、歩いて行けるね。' },
      { prompt: 'Ask someone to call you if they need help.', answer: 'If you need help, call me.', ja: '助けが必要なら、電話してね。' },
    ],
  },
];
